name = input('Enter Your Name:- ')
sbu = input('SBU:- ')
role = input('role:- ')
employeeid = input ('Employee ID:- ')
experience = input('Experience:- ')
print('Hello {0} Wellcome to universe Ltd. We are happy to know that you have {1} expreience. You will be part of {2} SBU & your role will be {3}. Your Employee ID in system is {4}'.format(name,experience,sbu,role,employeeid))
